forge:
  domain: flowfuse.dev
  https: true
  localPostgresql: true
  broker:
    enabled: true

postgresql:
  persistence:
    enabled: false
  primary:
    resources:
      requests:
        cpu: 1m
        memory: 1M
    nodeAffinityPreset:
      type: "hard"
      key: "role"
      values:
        - "management"
