forge:
  domain: flowfuse.dev
  https: true
  localPostgresql: true
  broker:
    enabled: true
  email:
    ses:
      region: eu-west-1
      

postgresql:
  persistence:
    enabled: false
  primary:
    nodeAffinityPreset:
      type: "hard"
      key: "role"
      values:
        - "management"
