name: Backend Tests

on:
  push:
    branches: [ main, maintenance ]
    paths:
      - 'forge/**'
      - 'test/unit/**'
      - 'test/system/**'
      - 'frontend/**'
      - 'test/e2e/frontend/**'
      - 'test/unit/frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.eslintrc'
  pull_request:
    paths:
      - 'forge/**'
      - 'test/unit/**'
      - 'test/system/**'
      - 'frontend/**'
      - 'test/e2e/frontend/**'
      - 'test/unit/frontend/**'
      - 'package.json'
      - '.eslintrc'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build the forge
      run: npm run build
    - name: Run forge unit tests
      run: npm run cover:unit:forge
    - name: Run forge system tests
      run: npm run cover:system
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: backend