name: Publish Documentation
on:
  push:
    branches: [ main, maintenance ]
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Documentation links
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Test Documentation Links
        run: npm run test:docs
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    name: Publish Documentation
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}
      
      - name: Trigger website rebuild
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: flowfuse/website
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
