name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.pull_request.title, 'Release')
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
