name: Release Published
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAINTENANCE_SYNC_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      # - run: npm run test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Resync Maintenance
        if: ${{ endsWith(github.ref, '.0') }}
        run: |
          git checkout maintenance
          git reset --hard origin/main
          git push --force origin maintenance
