name: UI E2E (Cypress) Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'test/e2e/frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'test/e2e/frontend/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: true
          config-file: config/cypress.config.js
          build: npm run build
          start: node test/e2e/frontend/test_environment.js
          
