name: Test Documentation Links
on:
  push:
    branches: [ main, maintenance ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      # Install NPM dependencies
      - name: Install Dependencies
        run: npm ci
      # Run Tests
      - run: npm run test:docs
